### ISSUE TITLE
Task for ODS - Prepare communications to inform stakeholders of the Aidstream-IATI Publisher integration

### ISSUE THREAD

**Issue by emmajclegg** [IATI/iatipublisher#1488]
ODS will start developing, with input from YI, communications around migrating AidStream users to IATI Publisher.

An initial comms plan is here: [Account migration plan: AidStream to IATI Publisher](https://docs.google.com/spreadsheets/d/17GsCBOXDgmYS56QGFAqAn7gbXjkXUEHFwuuIxW0yPnM/edit?gid=148203767#gid=148203767)
(this is not set in stone and can change as needed)

This includes direct messaging to AidStream users, IATI Publisher demos and drop-in support sessions for migrated users.

### Sub-tasks:
- [x] Prepare communications plan for 2024 (done - see link above)
- [x] Draft announcement to the IATI community on the integration work
- [ ] Draft message to be emailed to AidStream users directly 
- [ ] Notify donor governments of integration and what this means for their IATI guidance
- [ ] Notify other stakeholders that support other organisations to publish

**Comment by emmajclegg** [comment]
Closing as this work is on pause. A new issue will be created if and when needed.
